version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout 
      - run: echo "Hey! It's working!"
workflows:
  tests:
    jobs:
      - test
